---
mntpoints:
  - disk1
  - disk2
  - disk3
  - disk4
  - disk5
  - parity1
  - storage

dockeruser: dockeruser
dockergroup: dockergroup

appdata: /opt/appdata
downloaddir: /opt/downloads
dockerlist: /opt/docker.list
snapraidconf: /etc/snapraid.conf

mount_options:
  "/home": "defaults"
  "/mnt/disk1": "defaults"
  "/mnt/storage": "defaults,allow_other,minfreespace=50G,fsname=mergerfs"
